all:
  hosts:
    control-plane-1:
      ansible_host: 192.168.1.3
      ip: 192.168.1.3
      access_ip: 192.168.1.3
    control-plane-2:
      ansible_host: 192.168.1.4
      ip: 192.168.1.4
      access_ip: 192.168.1.4
    control-plane-3:
      ansible_host: 192.168.1.5
      ip: 192.168.1.5
      access_ip: 192.168.1.5
    worker-1:
      ansible_host: 192.168.1.6
      ip: 192.168.1.6
      access_ip: 192.168.1.6
  children:
    kube_control_plane:
      hosts:
        control-plane-1:
        control-plane-2:
        control-plane-3:
    etcd:
      hosts:
        control-plane-1:
        control-plane-2:
        control-plane-3:
    kube_node:
      hosts:
        worker-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
